import { createRouter, createWebHistory ,createWebHashHistory} from 'vue-router'

const routes = [
  {
    path: '/',
    redirect:'/systemUserManage',
    component: () => import('../views/main.vue'),
    meta:{
      isAuth:false
    },
    children:[{
      path:'/systemUserManage',
      name:'systemUserManage',
      meta:{
        isAuth:true,
        title:'用户管理',
        parentName:'系统管理'
      },
      component:()=>import('../views/systemUserManage/index.vue')
    },{
      path:'/systemCustomer',
      name:'systemCustomer',
      meta:{
        isAuth:true,
        title:'客户资料',
        parentName:'系统管理'
      },
      component:()=>import('../views/systemCustomer/index.vue')
    },{
      path:'/systemLanguage',
      name:'systemLanguage',
      meta:{
        isAuth:true,
        title:'语言管理',
        parentName:'系统管理'
      },
      component:()=>import('../views/systemLanguage/index.vue')
    },{
      path:'/systemCallLog',
      name:'systemCallLog',
      meta:{
        isAuth:true,
        title:'打卡记录',
        parentName:'系统管理'
      },
      component:()=>import('../views/systemCallLog/index.vue')
    },{
      path:'/systemOperationLog',
      name:'systemOperationLog',
      meta:{
        isAuth:true,
        title:'操作日志',
        parentName:'系统管理'
      },
      component:()=>import('../views/systemOperationLog/index.vue')
    },{
      path:'/systemDatabase',
      name:'systemDatabase',
      meta:{
        isAuth:true,
        title:'数据库管理',
        parentName:'系统管理'
      },
      component:()=>import('../views/systemDatabase/index.vue')
    },{
      path:'/restaurantDetail',
      name:'restaurantDetail',
      meta:{
        isAuth:true,
        title:'餐厅信息',
        parentName:'餐厅管理'
      },
      component:()=>import('../views/restaurantDetail/index.vue')
    },{
      path:'/restaurantConfig',
      name:'restaurantConfig',
      meta:{
        isAuth:true,
        title:'基础配置',
        parentName:'餐厅管理'
      },
      component:()=>import('../views/restaurantConfig/index.vue')
    },{
      path:'/restaurantTaxRate',
      name:'restaurantTaxRate',
      meta:{
        isAuth:true,
        title:'税率',
        parentName:'餐厅管理'
      },
      component:()=>import('../views/restaurantTaxRate/index.vue')
    },{
      path:'/restaurantDiscount',
      name:'restaurantDiscount',
      meta:{
        isAuth:true,
        title:'折扣',
        parentName:'餐厅管理'
      },
      component:()=>import('../views/restaurantDiscount/index.vue')
    },{
      path:'/restaurantService',
      name:'restaurantService',
      meta:{
        isAuth:true,
        title:'服务费',
        parentName:'餐厅管理'
      },
      component:()=>import('../views/restaurantService/index.vue')
    },{
      path:'/productClassification',
      name:'productClassification',
      meta:{
        isAuth:true,
        title:'分类管理',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productClassification/index.vue')
    },{
      path:'/productCombination',
      name:'productCombination',
      meta:{
        isAuth:true,
        title:'组合管理',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productCombination/index.vue')
    },{
      path:'/condimentClassify',
      name:'condimentClassify',
      meta:{
        isAuth:true,
        title:'调味品组合',
        parentName:'调味品管理'
      },
      component:()=>import('../views/condimentClassify/index.vue')
    },{
      path:'/condimentItem',
      name:'condimentItem',
      meta:{
        isAuth:true,
        title:'调味品',
        parentName:'调味品管理'
      },
      component:()=>import('../views/condimentItem/index.vue')
    },{
      path:'/condimentCustom',
      name:'condimentCustom',
      meta:{
        isAuth:true,
        title:'自定义调味品',
        parentName:'调味品管理'
      },
      component:()=>import('../views/condimentCustom/index.vue')
    },{
      path:'/productManage',
      name:'productManage',
      meta:{
        isAuth:true,
        title:'菜品管理',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productManage/index.vue')
    },{
      path:'/productManageAction',
      name:'productManageAction',
      meta:{
        isAuth:true,
        title:'菜品管理-操作',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productManage/action.vue')
    },{
      path:'/productStock',
      name:'productStock',
      meta:{
        isAuth:true,
        title:'库存管理',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productStock/index.vue')
    },{
      path:'/productStockLog',
      name:'productStockLog',
      meta:{
        isAuth:true,
        title:'库存记录',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productStock/log.vue')
    },{
      path:'/productPackage',
      name:'productPackage',
      meta:{
        isAuth:true,
        title:'套餐管理',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productPackage/index.vue')
    },{
      path:'/productPackageAction',
      name:'productPackageAction',
      meta:{
        isAuth:true,
        title:'套餐管理-操作',
        parentName:'菜品管理'
      },
      component:()=>import('../views/productPackage/action.vue')
    },{
      path:'/restaurantPaymentMethod',
      name:'restaurantPaymentMethod',
      meta:{
        isAuth:true,
        title:'付款方式',
        parentName:'餐厅管理'
      },
      component:()=>import('../views/restaurantPaymentMethod/index.vue')
    },{
      path:'/activityTimeLimit',
      name:'activityTimeLimit',
      meta:{
        isAuth:true,
        title:'限时活动',
        parentName:'活动管理'
      },
      component:()=>import('../views/activityTimeLimit/index.vue')
    },{
      path:'/activityTimeLimitAction',
      name:'activityTimeLimitAction',
      meta:{
        isAuth:true,
        title:'限时活动-操作',
        parentName:'活动管理'
      },
      component:()=>import('../views/activityTimeLimit/action.vue')
    },{
      path:'/activityDiscount',
      name:'activityDiscount',
      meta:{
        isAuth:true,
        title:'优惠活动',
        parentName:'活动管理'
      },
      component:()=>import('../views/activityDiscount/index.vue')
    },{
      path:'/activityDiscountAction',
      name:'activityDiscountAction',
      meta:{
        isAuth:true,
        title:'优惠活动-操作',
        parentName:'活动管理'
      },
      component:()=>import('../views/activityDiscount/action.vue')
    },{
      path:'/orderManage',
      name:'orderManage',
      meta:{
        isAuth:true,
        title:'订单管理',
        parentName:'订单管理'
      },
      component:()=>import('../views/orderManage/index.vue')
    },{
      path:'/orderManageDetail',
      name:'orderManageDetail',
      meta:{
        isAuth:true,
        title:'订单详情',
        parentName:'订单管理'
      },
      component:()=>import('../views/orderManage/components/detail.vue')
    },{
      path:'/deviceCustomTic',
      name:'deviceCustomTic',
      meta:{
        isAuth:true,
        title:'自定义小票',
        parentName:'硬件管理'
      },
      component:()=>import('../views/deviceCustomTic/index.vue')
    },{
      path:'/devicePrinter',
      name:'devicePrinter',
      meta:{
        isAuth:true,
        title:'后厨打印机',
        parentName:'硬件管理'
      },
      component:()=>import('../views/devicePrinter/index.vue')
    },{
      path:'/devicePrinterBefore',
      name:'devicePrinterBefore',
      meta:{
        isAuth:true,
        title:'前台打印机',
        parentName:'硬件管理'
      },
      component:()=>import('../views/devicePrinterBefore/index.vue')
    },
    {
      path:'/reportForm',
      name:'reportForm',
      meta:{
        isAuth:true,
        title:'报表管理',
        parentName:'报表管理'
      },
      component:()=>import('../views/reportForm/index.vue')
    },{
      path:'/reportFormLog',
      name:'reportFormLog',
      meta:{
        isAuth:true,
        title:'报表明细',
        parentName:'报表管理'
      },
      component:()=>import('../views/reportFormLog/index.vue')
    }]
    
  },{
    path: '/login',
    meta:{
      isAuth:false
    },
    component: () => import('../views/login.vue')
  },{
    path: '/404',
    meta:{
      isAuth:false
    },
    component: () => import('../views/404.vue')
  }
]

const router = createRouter({
  history: createWebHashHistory(process.env.BASE_URL),
  routes
})

export default router
